In [1]:
import pandas as pd
import numpy as np

In [3]:
## test test test


#I created the citibike_station_info.csv file using data from url: https://feeds.citibikenyc.com/stations/stations.json
# Please run the code below to view the data frame

fname = 'citibike_station_info.csv'
df_cb = pd.read_csv(fname)
df_cb.head(20)   #change the numbers of rows you want to view

,Station_id,Station_Name,Location,Latitude,Longitude,Total_Docks,Available_Docks,Available_Bikes,lastCommunicationTime,Status,Test_Station,Status_Key
0,72,W 52 St & 11 Ave,W 52 St & 11 Ave,40.767272,-73.993929,39,33,6,2016-09-22 03:37:02 PM,In Service,False,1
1,79,Franklin St & W Broadway,Franklin St & W Broadway,40.719116,-74.006667,33,8,24,2016-09-22 03:35:04 PM,In Service,False,1
2,82,St James Pl & Pearl St,St James Pl & Pearl St,40.711174,-74.000165,27,25,2,2016-09-22 03:35:13 PM,In Service,False,1
3,83,Atlantic Ave & Fort Greene Pl,Atlantic Ave & Fort Greene Pl,40.683826,-73.976323,62,39,22,2016-09-22 03:35:32 PM,In Service,False,1
4,116,W 17 St & 8 Ave,W 17 St & 8 Ave,40.741776,-74.001497,39,34,4,2016-09-22 03:36:14 PM,In Service,False,1
5,119,Park Ave & St Edwards St,Park Ave & St Edwards St,40.696089,-73.978034,19,11,8,2016-09-22 03:36:43 PM,In Service,False,1
6,120,Lexington Ave & Classon Ave,Lexington Ave & Classon Ave,40.686768,-73.959282,19,14,4,2016-09-22 03:36:53 PM,In Service,False,1
7,127,Barrow St & Hudson St,Barrow St & Hudson St,40.731724,-74.006744,31,6,20,2016-09-22 03:34:13 PM,In Service,False,1
8,128,MacDougal St & Prince St,MacDougal St & Prince St,40.727103,-74.002971,30,12,18,2016-09-22 03:35:01 PM,In Service,False,1
9,137,E 56 St & Madison Ave,E 56 St & Madison Ave,40.761628,-73.972924,46,27,18,2016-09-22 03:37:31 PM,In Service,False,1
10,143,Clinton St & Joralemon St,Clinton St & Joralemon St,40.692395,-73.993379,24,5,19,2016-09-22 03:34:51 PM,In Service,False,1
11,144,Nassau St & Navy St,Nassau St & Navy St,40.698399,-73.980689,19,4,14,2016-09-22 03:36:24 PM,In Service,False,1
12,146,Hudson St & Reade St,Hudson St & Reade St,40.716250,-74.009106,39,20,16,2016-09-22 03:33:57 PM,In Service,False,1
13,147,Greenwich St & Warren St,Greenwich St & Warren St,40.715422,-74.011220,33,3,30,2016-09-22 03:36:50 PM,In Service,False,1
14,150,E 2 St & Avenue C,E 2 St & Avenue C,40.720874,-73.980858,31,19,12,2016-09-22 03:37:31 PM,In Service,False,1
15,151,Cleveland Pl & Spring St,Cleveland Pl & Spring St,40.722104,-73.997249,33,13,18,2016-09-22 03:36:33 PM,In Service,False,1
16,152,Warren St & Church St,Warren St & Church St,40.714740,-74.009106,29,0,28,2016-09-22 03:37:19 PM,In Service,False,1
17,153,E 40 St & 5 Ave,E 40 St & 5 Ave,40.752062,-73.981632,55,21,34,2016-09-22 03:37:27 PM,In Service,False,1
18,157,Henry St & Atlantic Ave,Henry St & Atlantic Ave,40.690893,-73.996123,23,17,6,2016-09-22 03:35:18 PM,In Service,False,1
19,161,LaGuardia Pl & W 3 St,LaGuardia Pl & W 3 St,40.729170,-73.998102,35,2,33,2016-09-22 03:36:08 PM,In Service,False,1